version: "3.8"

services:
  frontend:
    build:
      context: .  # Build from the local directory
      dockerfile: Dockerfile
    image: mehmetgencv/kasyus-fe:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:8082
